schema_version = "1.0.0"
version = "1.0.0"
name = "Texture Manager"
tagline = "Bake, Pack, Invert & Auto-Import to Unity—All in One Blender Too"
id = "texture_manager"
wheels=['./wheels/imageio-2.37.0-py3-none-any.whl', './wheels/opencv_python-4.11.0.86-cp311-abi3-macosx_13_0_arm64.whl', './wheels/opencv_python-4.11.0.86-cp311-abi3-macosx_13_0_x86_64.whl', './wheels/opencv_python-4.11.0.86-cp311-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl', './wheels/opencv_python-4.11.0.86-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', './wheels/opencv_python-4.11.0.86-cp311-abi3-win_amd64.whl', './wheels/pillow-11.2.1-cp311-cp311-macosx_10_13_x86_64.whl', './wheels/pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl', './wheels/pillow-11.2.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl', './wheels/pillow-11.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', './wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl']

maintainer = "Mr.Volcano <greenbellpaper13@gmail.com>"

license = [
  "SPDX:GPL-3.0-or-later",
]
type = "add-on"

tags = [
	"Game Engine",
	"Bake",
	"Material",
	"UV",
]
blender_version_min = "4.2.0"


platforms = ["windows-x64", "macos-arm64", "linux-x64","macos-x64"]

